### ISSUE TITLE
Generate task help output from docstrings

### ISSUE THREAD

**Issue by DeflatedPickle** [pyrsmk/run#1]
It would be nice to be able to annotate tasks with a string that would be printed when that task was called along with a `-h`. I found an implementation of how this could be done [here](https://stackoverflow.com/a/2948977)

**Comment by pyrsmk** [comment]
Oh my god I never saw this issue pop up! Sorry for the late anwser!

Anyway, I don't remember how the implementation was at the time you open the ticket (because it has change a lot), but you can define a description string when writing a task.

Nevertheless, the task description is not printed on call, I don't know if it's really necessary. I'm open to arguments on this matter ;)

**Comment by DeflatedPickle** [comment]
I realised that after.. but it still looks and feels nicer to annotate the task with a doc string, personally. Might be nice if arguments are ever added too? Anyway I worked a little in my fork so that it does print out the help strings when the script is called with no args or with `-h` and maybe I did other things. Can't remember

**Comment by pyrsmk** [comment]
By design, I'm not really in favor of adding annotations because it would make the code a bit more complex.

> Might be nice if arguments are ever added too?

They're already there ;) I advise you to read the README. Many improvements have been made in the last couple of months.
